# Generated by Django 3.0.8 on 2020-07-21 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200720_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
